export const LANGUAGES = [
	{ code: "ar", code3: "ara", name: "Arabic" },
	{ code: "bn", code3: "ben", name: "Bengali" },
	{ code: "bg", code3: "bul", name: "Bulgarian" },
	{ code: "ca", code3: "cat", name: "Catalan" },
	{ code: "zh", code3: "cmn", name: "Chinese (Mandarin)" },
	{ code: "hr", code3: "hrv", name: "Croatian" },
	{ code: "cs", code3: "ces", name: "Czech" },
	{ code: "da", code3: "dan", name: "Danish" },
	{ code: "nl", code3: "nld", name: "Dutch" },
	{ code: "en", code3: "eng", name: "English" },
	{ code: "et", code3: "est", name: "Estonian" },
	{ code: "fi", code3: "fin", name: "Finnish" },
	{ code: "fr", code3: "fra", name: "French" },
	{ code: "de", code3: "deu", name: "German" },
	{ code: "el", code3: "ell", name: "Greek" },
	{ code: "he", code3: "heb", name: "Hebrew" },
	{ code: "hi", code3: "hin", name: "Hindi" },
	{ code: "hu", code3: "hun", name: "Hungarian" },
	{ code: "id", code3: "ind", name: "Indonesian" },
	{ code: "it", code3: "ita", name: "Italian" },
	{ code: "ja", code3: "jpn", name: "Japanese" },
	{ code: "ko", code3: "kor", name: "Korean" },
	{ code: "lv", code3: "lav", name: "Latvian" },
	{ code: "lt", code3: "lit", name: "Lithuanian" },
	{ code: "ms", code3: "msa", name: "Malay" },
	{ code: "nb", code3: "nob", name: "Norwegian (Bokmål)" },
	{ code: "fa", code3: "fas", name: "Persian" },
	{ code: "pl", code3: "pol", name: "Polish" },
	{ code: "pt", code3: "por", name: "Portuguese" },
	{ code: "ro", code3: "ron", name: "Romanian" },
	{ code: "ru", code3: "rus", name: "Russian" },
	{ code: "sr", code3: "srp", name: "Serbian" },
	{ code: "sk", code3: "slk", name: "Slovak" },
	{ code: "sl", code3: "slv", name: "Slovenian" },
	{ code: "es", code3: "spa", name: "Spanish" },
	{ code: "sv", code3: "swe", name: "Swedish" },
	{ code: "tl", code3: "tgl", name: "Tagalog" },
	{ code: "th", code3: "tha", name: "Thai" },
	{ code: "tr", code3: "tur", name: "Turkish" },
	{ code: "uk", code3: "ukr", name: "Ukrainian" },
	{ code: "ur", code3: "urd", name: "Urdu" },
	{ code: "vi", code3: "vie", name: "Vietnamese" },
] as const

export type LanguageCode = (typeof LANGUAGES)[number]["code"]
